package exactlyonce

import java.util.Properties

import kafka.producer.{KeyedMessage, Producer, ProducerConfig}
import org.apache.kafka.clients.producer.{Callback, ProducerRecord, RecordMetadata}

import scala.util.Random


object ExactlyOnceProducerTest {

  var kafkaHost = "localhost:9092"
  def main(args: Array[String]): Unit = {
    if(args.length>0) {
      kafkaHost = args(0)
    }
  }

  object kafka {
    lazy val producer = {
      val props = new Properties()
      props.put("bootstrap.servers", kafkaHost)
      props.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer")
      props.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer")
      import org.apache.kafka.clients.producer.KafkaProducer
      new KafkaProducer[Nothing, String](props)
    }
  }

  val test = Random
  for (i <- 1 to 1000000) {

    //    val message =  new KeyedMessage[String, String]("exactlyonce", test.nextString(50)+ "aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf " +
    //      "aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf " +
    //      "aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf " +
    //      "aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf " +
    //      "aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf " +
    //      "aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf " +
    //      "aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf " +
    //      "aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf " +
    //      "aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf " +
    //      "aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf " +
    //      "aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf " +
    //      "aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf " +
    //      "aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf aze sdq sdfs dkfgjlk djhgn;kdsfn g;s,sdnfgbs ;,dfngbs jdfhgb kuugf ")

    //val message = new ProducerRecord("exactlyonce", s"""{"name": "${test.nextString(50)}", "age": ${test.nextInt(99)}}""")
    val message = new ProducerRecord("exactlyonce", s"""{"name": "${Random.alphanumeric take 10 mkString("")}", "age": ${test.nextInt(99)}}""")
    println(System.currentTimeMillis())
    kafka.producer.send(message, new Callback {
      override def onCompletion(metadata: RecordMetadata, exception: Exception): Unit = {

      }
    })
    if (i%1000 ==0){
      println(System.currentTimeMillis())
    }
    Thread.sleep(300)
    //println(message)
  }
  println("closing")
  kafka.producer.close()
  println("closed")
}

